export type Suitability = "YES" | "POSSIBLY" | "NOT GENERALLY";

export type Treatment = {
  slug: string;
  category: string;
  name: string;
  suitability: Suitability;
  why: string;
  summary: string;
  usNotes: string;
  indiaNotes: string;
};

export const TREATMENTS: Treatment[] = [
  {
    slug: "knee-replacement",
    category: "Orthopedics",
    name: "Knee replacement",
    suitability: "YES",
    why: "Typically elective, with a defined recovery window that many patients can plan around if they are medically fit to travel.",
    summary: "Replacement of a damaged knee joint with an implant. Often considered when pain and function no longer respond to conservative care.",
    usNotes: "What you may need to pay yourself depends on your healthcare coverage or funding, not the hospital sticker price.",
    indiaNotes: "Indicative hospital ranges vary widely by implant, city and length of stay. The relevant number is the complete journey cost.",
  },
  {
    slug: "hip-replacement",
    category: "Orthopedics",
    name: "Hip replacement",
    suitability: "YES",
    why: "Usually planned. Travel is only appropriate after a clinician confirms fitness to fly before and after surgery.",
    summary: "Replacement of a damaged hip joint. Recovery and dislocation precautions matter for the return flight.",
    usNotes: "What you pay yourself can still be high even when coverage pays a large share of billed charges.",
    indiaNotes: "Stay length in India is often driven by physiotherapy and surgeon clearance to fly, not only the hospital invoice.",
  },
  {
    slug: "spine-surgery",
    category: "Orthopedics",
    name: "Spine surgery",
    suitability: "POSSIBLY",
    why: "Some elective spine procedures may be planned internationally; others require urgent local care or intensive follow-up.",
    summary: "A wide family of procedures. Suitability depends on diagnosis, neurology, and the ability to travel safely.",
    usNotes: "Authorization and specialist wait times vary. Sticker prices are a poor proxy for what you may need to pay yourself.",
    indiaNotes: "Requires individual clinical review before any travel discussion.",
  },
  {
    slug: "shoulder-replacement",
    category: "Orthopedics",
    name: "Shoulder replacement",
    suitability: "POSSIBLY",
    why: "Often elective, but rehabilitation and companion support affect whether travel is practical.",
    summary: "Joint replacement for selected shoulder conditions after conservative care has been considered.",
    usNotes: "Coverage and what you may need to pay yourself vary by healthcare system and plan.",
    indiaNotes: "Journey cost must include stay, companion, and follow-up, not only the implant invoice.",
  },
  {
    slug: "cabg",
    category: "Cardiology",
    name: "CABG / heart bypass",
    suitability: "POSSIBLY",
    why: "Only after careful clinical review. Unstable cardiac disease is not a medical-travel case.",
    summary: "Coronary artery bypass grafting is major surgery. Fitness to travel and postoperative monitoring are decisive.",
    usNotes: "Billed charges can be very large. What you pay yourself still depends on the health system and plan where you live.",
    indiaNotes: "DCredit will not recommend travel simply because a quote is lower. Clinical safety comes first.",
  },
  {
    slug: "valve-replacement",
    category: "Cardiology",
    name: "Valve replacement",
    suitability: "POSSIBLY",
    why: "May be planned in selected stable patients. Emergency valve presentations are not coordinated internationally.",
    summary: "Surgical or transcatheter valve procedures require specialist evaluation of anatomy, risk and follow-up.",
    usNotes: "Prior authorization and specialist-network rules can change both access and cost.",
    indiaNotes: "Individual hospital capability, ICU and emergency backup must be evaluated, not assumed.",
  },
  {
    slug: "angioplasty",
    category: "Cardiology",
    name: "Angioplasty",
    suitability: "NOT GENERALLY",
    why: "Often time-sensitive. Acute coronary syndromes require immediate local emergency care.",
    summary: "Catheter-based treatment of coronary artery disease. Emergencies are not DCredit cases.",
    usNotes: "If you have chest pain or a suspected heart attack, use the emergency number where you are.",
    indiaNotes: "Elective, stable cases still require individual review by a qualified clinician before any travel discussion.",
  },
  {
    slug: "structural-heart",
    category: "Cardiology",
    name: "Structural heart procedures",
    suitability: "POSSIBLY",
    why: "Highly case-specific. Not marketed as a default medical-travel product.",
    summary: "Includes selected valve and structural interventions after imaging and heart-team review.",
    usNotes: "Pricing and coverage are procedure- and plan-specific.",
    indiaNotes: "Provider evaluation is individual. Accreditation is not an outcome guarantee.",
  },
  {
    slug: "cancer-surgery",
    category: "Oncology",
    name: "Cancer surgery",
    suitability: "POSSIBLY",
    why: "Some planned oncology pathways may be coordinated; others must stay with the current care team at home.",
    summary: "Surgical oncology is not a single product. Staging, adjuvant therapy and follow-up determine travel sense.",
    usNotes: "Continuity with an oncologist at home after return is part of the decision, not an afterthought.",
    indiaNotes: "DCredit does not independently diagnose or prescribe oncology treatment.",
  },
  {
    slug: "radiation",
    category: "Oncology",
    name: "Radiation",
    suitability: "POSSIBLY",
    why: "Fractionated schedules can require a long stay. Not automatically cheaper or better.",
    summary: "Radiation therapy plans are protocol-specific and must be reviewed by qualified clinicians.",
    usNotes: "What you may need to pay yourself depends on coverage design and in-network or approved-provider rules.",
    indiaNotes: "Total journey cost includes lodging for the full treatment course.",
  },
  {
    slug: "chemotherapy",
    category: "Oncology",
    name: "Chemotherapy",
    suitability: "POSSIBLY",
    why: "Cycles, supportive care and lab monitoring may make international travel impractical.",
    summary: "Systemic cancer therapy is coordinated only when clinically and logistically appropriate.",
    usNotes: "Drug coverage and site-of-care rules often dominate what you pay yourself.",
    indiaNotes: "Return-home follow-up must be planned before travel is considered.",
  },
  {
    slug: "immunotherapy",
    category: "Oncology",
    name: "Immunotherapy",
    suitability: "POSSIBLY",
    why: "Indication, monitoring and cost structure vary. Not a default travel pathway.",
    summary: "Requires individual review of protocol, toxicity monitoring and continuity of care by a qualified clinician.",
    usNotes: "Prices and coverage are highly plan-specific.",
    indiaNotes: "Estimates are labeled as estimates until a named provider issues a plan.",
  },
  {
    slug: "targeted-therapy",
    category: "Oncology",
    name: "Targeted therapy",
    suitability: "POSSIBLY",
    why: "Depends on molecular indication, drug access and monitoring, not on a brochure price.",
    summary: "Precision oncology decisions belong with qualified clinicians, not a website.",
    usNotes: "Prior authorization often determines what you may need to pay yourself.",
    indiaNotes: "Drug availability and follow-up labs must be confirmed, not assumed.",
  },
  {
    slug: "ivf",
    category: "Fertility",
    name: "IVF",
    suitability: "YES",
    why: "Typically planned. Many patients compare cycle costs, stay length and clinic protocols.",
    summary: "In vitro fertilization. Success rates are not guaranteed in any country.",
    usNotes: "Coverage for IVF is uneven in many countries. Patient responsibility is often close to the cash price.",
    indiaNotes: "Compare complete cycle plus stay, not a single advertised package line.",
  },
  {
    slug: "icsi",
    category: "Fertility",
    name: "ICSI",
    suitability: "YES",
    why: "Usually planned with IVF. Suitability is clinical, not geographic.",
    summary: "Intracytoplasmic sperm injection as part of an assisted-reproduction pathway.",
    usNotes: "Add-on fees at home can change the real patient cost.",
    indiaNotes: "Ask what is included, excluded, and how many cycles the estimate covers.",
  },
  {
    slug: "fertility-evaluation",
    category: "Fertility",
    name: "Fertility evaluation",
    suitability: "YES",
    why: "Diagnostic work-ups can sometimes be planned internationally, or used to inform a decision at home.",
    summary: "Testing and consultation to understand fertility options. Not a diagnosis from DCredit.",
    usNotes: "Work-up costs vary by clinic and healthcare coverage or funding.",
    indiaNotes: "Records should travel both ways so a clinician at home can continue care.",
  },
  {
    slug: "dental-implants",
    category: "Dentistry",
    name: "Dental implants",
    suitability: "YES",
    why: "Common planned dental-travel case when cash prices at home are high and staging can be scheduled.",
    summary: "Implant placement and restoration. May require more than one visit.",
    usNotes: "Dental benefits are often limited. Patient cash exposure can be large.",
    indiaNotes: "Count flights for possible second-stage visits, not only the first invoice.",
  },
  {
    slug: "full-mouth",
    category: "Dentistry",
    name: "Full-mouth rehabilitation",
    suitability: "POSSIBLY",
    why: "Complex, staged, and dependent on how long you can stay and on quality of follow-up at home.",
    summary: "Comprehensive restorative dentistry. Not a single appointment.",
    usNotes: "Quotes vary widely. Coverage may pay little.",
    indiaNotes: "A complete journey estimate must include staging, stay and revisions.",
  },
  {
    slug: "crowns-bridges",
    category: "Dentistry",
    name: "Crowns and bridges",
    suitability: "YES",
    why: "Often elective and schedulable, if the clinical plan is clear.",
    summary: "Restorative dentistry. Quality and laboratory work matter as much as price.",
    usNotes: "Annual dental maximums, where they exist, often leave patients paying cash.",
    indiaNotes: "Ask about materials, laboratory, and what happens if a restoration fails after you return.",
  },
  {
    slug: "cataract",
    category: "Eye care",
    name: "Cataract",
    suitability: "YES",
    why: "Typically planned. Postoperative drop regimens and follow-up must be workable after return.",
    summary: "Lens replacement for cataract. Not an emergency pathway.",
    usNotes: "Public and private coverage where you live can change what you pay substantially.",
    indiaNotes: "India may not be cheaper after insurance. That is a reason to compare real exposure.",
  },
  {
    slug: "refractive",
    category: "Eye care",
    name: "Refractive procedures",
    suitability: "YES",
    why: "Usually elective and self-pay in many countries, so a full-journey comparison can be informative.",
    summary: "Vision-correction procedures. Outcomes are not guaranteed.",
    usNotes: "Often paid cash at home.",
    indiaNotes: "Enhancement policy and follow-up after return should be written down before travel.",
  },
  {
    slug: "retina",
    category: "Eye care",
    name: "Retina procedures",
    suitability: "POSSIBLY",
    why: "Some are planned; others are time-sensitive. Individual clinical review is required.",
    summary: "Retinal care ranges from injections to surgery. Emergencies belong in local care.",
    usNotes: "Coverage and copays vary by injection versus surgery.",
    indiaNotes: "Travel is inappropriate when delay risks vision.",
  },
  {
    slug: "brain-surgery",
    category: "Neurology / neurosurgery",
    name: "Brain surgery",
    suitability: "NOT GENERALLY",
    why: "Many neurosurgical cases are urgent or require immediate local intervention.",
    summary: "Not a default medical-travel product. Selected planned cases need individual review by a qualified clinician.",
    usNotes: "If this is an emergency, seek local emergency care.",
    indiaNotes: "DCredit does not coordinate emergencies.",
  },
  {
    slug: "movement-disorders",
    category: "Neurology / neurosurgery",
    name: "Movement disorders",
    suitability: "POSSIBLY",
    why: "Selected planned evaluations or procedures may be appropriate; others are not.",
    summary: "Requires specialist assessment of diagnosis, device follow-up and travel risk.",
    usNotes: "Networks and authorization rules shape access and cost.",
    indiaNotes: "Programming and follow-up after return must be realistic.",
  },
  {
    slug: "kidney-stones",
    category: "Urology",
    name: "Kidney stone procedures",
    suitability: "POSSIBLY",
    why: "Elective stone work may be planned; obstructing or infected stones are emergencies.",
    summary: "Procedure choice depends on stone size, location and infection risk.",
    usNotes: "Acute obstruction is not an international-travel situation.",
    indiaNotes: "Fever, obstruction or sepsis requires local emergency care.",
  },
  {
    slug: "prostate",
    category: "Urology",
    name: "Prostate procedures",
    suitability: "POSSIBLY",
    why: "Some planned procedures can be compared; cancer pathways need oncology-style review.",
    summary: "Ranges from benign obstruction procedures to cancer surgery. Not one product.",
    usNotes: "What you may need to pay yourself depends on setting and coverage design.",
    indiaNotes: "Pathology, staging and follow-up must be part of any plan.",
  },
  {
    slug: "kidney-transplant",
    category: "Transplant",
    name: "Kidney transplant",
    suitability: "NOT GENERALLY",
    why: "Transplant involves organ-allocation, legal, ethical and long-term immunosuppression issues that are not a simple price comparison.",
    summary: "DCredit does not market transplant as a packaged medical-tourism product.",
    usNotes: "Transplant is highly regulated in many countries. Travel for transplant requires specialist legal and clinical advice.",
    indiaNotes: "Organ transplantation is subject to Indian law. We will not imply that travel is automatically appropriate.",
  },
  {
    slug: "liver-transplant",
    category: "Transplant",
    name: "Liver transplant",
    suitability: "NOT GENERALLY",
    why: "Not a standard elective medical-travel offering. Legal and clinical constraints are substantial.",
    summary: "Requires specialized transplant programs and long-term follow-up.",
    usNotes: "Not an emergency-avoidance shortcut.",
    indiaNotes: "DCredit will not recommend transplant travel solely because a quote appears lower.",
  },
];

export function treatmentBySlug(slug: string) {
  return TREATMENTS.find((t) => t.slug === slug) ?? null;
}

export const CATEGORIES = [...new Set(TREATMENTS.map((t) => t.category))];

/** Editorial labels, not a clinical determination for any individual patient. */
export const SUITABILITY_LABEL: Record<Suitability, string> = {
  YES: "Often considered in international planned-care discussions",
  POSSIBLY: "May be worth exploring. Requires individual clinical review",
  "NOT GENERALLY": "Not appropriate for emergency situations or as a default travel pathway",
};

export function suitabilityClass(s: Suitability) {
  if (s === "YES") return "flag flag-yes";
  if (s === "POSSIBLY") return "flag flag-maybe";
  return "flag flag-no";
}
